### ISSUE TITLE
Not connecting to vMix

### ISSUE THREAD

**Issue by crambow** [jensstigaard/node-vmix#12]
I can't get my app to connect to vMix over ConnectionTCP class. 
I copied the code from the Quick Start section, but no events are getting executed.

When turning on debug mode I get the following output:
```
[node-vmix] Instanciating TCP socket to vMix instance localhost
[node-vmix] Received host localhost
[node-vmix] Received options {
  debug: true,
  debugBuffers: true
}
[node-vmix] -----
[node-vmix] Attempting to establish TCP socket connection to vMix instance localhost:8099
[node-vmix] TCP socket connection to vMix instance was already established... localhost:8099
```
It says that the connection is established, but non of the events are getting fired. It gives the same output even when vMix is closed.

If I try to send a command like `connection.send({ Function: 'Cut' })` the following error occurs:
```
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:775:8)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at ConnectionTCP._sendMessageToSocket (.\node_modules\node-vmix\src\modules\connection-tcp.ts:697:22)
    at ConnectionTCP.send (.\node_modules\node-vmix\src\modules\connection-tcp.ts:769:21)
    at Object.<anonymous> (.\src\index.ts:39:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (.\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

Happened when using Typescript and also when using Javascript as language.

Of course I checked that vMix is up & running. Had no issues trying to connect to vMix with ncat client.
OS: Win10

**Comment by olzzon** [comment]
Hi crambow,
Is "telnet localhost 8099" connecting?
Although socket connection is not connected you can still send commands but will get an error.
And put a console.log in the 'connect' callback like this:
```
connection.on('connect', () => {
  console.log('Socket Connected to Vmix')
  connection.send('TALLY');
});
```

**Comment by crambow** [comment]
Telnet works for me! I am able to control and receive messages from vMix without any issues via telnet.

The console output is not printed. The software also does not halt after the start up. It is getting closed as soon as my code has been completely run through.

**Comment by olzzon** [comment]
I would try something like:
```
connection.connect()
```
as the last line in you code.

You need to initialize the connection after setting it up.
@jensstigaard  isn´t this missing in the README.md example? Or should it work without?

**Comment by jensstigaard** [comment]
@olzzon Actually .connect() is not required to be called manually unless the option '`disableAutoConnectOnInit`' is enabled on options on `new ConnectionTCP(host, options)`
Note: Previously the option was named otherwisely. I have just renamed this option to make it more clear that by default the connection is automatically attempted to be established.
Therefore it is not stated anywhere in the examples that .connect() should be called. 

@crambow
I have added a minimal example of using a native TCP socket to connect. Please try run this and see if it connects.

```typescript
import Socket from 'net'

const client = Socket.createConnection(
	{ host: 'localhost', port: 8099 },
	() => { console.log('Msg upon initiazation') }
)

client.on('connect', (err: any) => {
	if (err) {
		console.error(err)
		return
	}
	console.log('Connected!')
})

client.on('data', (data: Buffer) => {
	const str = data.toString('utf8')
	console.log('Received data!', str)
})

```

**Comment by crambow** [comment]
@jensstigaard 
Your code works fine and I get the following output:
```
Msg upon initiazation
Connected!
Received data! VERSION OK 24.0.0.58
```

When I got some time I'm going to test it on antoher computer...

@olzzon 
As I mentioned in [this post](https://github.com/jensstigaard/node-vmix/issues/12#issuecomment-838596144), I already tried to call `connection.connect()`. I tried it again today but no success.

**Comment by supermomme** [comment]
I got that issue yesterday too. The issue is, that the method connected() returns true, even if it is not connected properly.
My workaround for the issue was to remove `if (this.connected()) ...`-check in the connect() method.
I know this workaround is not beatiful, but i hope i helped you investigating the issue.
i posted my code on a fork: https://github.com/codeanker/node-vmix

btw. i am using node v15.10.0

**Comment by jensstigaard** [comment]
@crambow I have just released version 1.5.2 which hopefully fixes the issue that you are facing.

Please report back whether it works for you or not.

**Comment by jensstigaard** [comment]
> I got that issue yesterday too. The issue is, that the method connected() returns true, even if it is not connected properly.
> My workaround for the issue was to remove `if (this.connected()) ...`-check in the connect() method.
> I know this workaround is not beatiful, but i hope i helped you investigating the issue.
> i posted my code on a fork: [codeanker/node-vmix](https://github.com/codeanker/node-vmix)
> 
> btw. i am using node v15.10.0

And thanks to @supermomme for the report on this. I tested out the native socket functionality, and found it worked differently than I originally thought in regard to .readyState and buffering of messages on sockets not yet connected. 
Hopefully the brand newly release should fix the issue.

**Comment by supermomme** [comment]
yes it is connecting now. thanks!

**Comment by crambow** [comment]
Works fine now, thanks!
