### ISSUE TITLE
acts event is never called

### ISSUE THREAD

**Issue by gamerxp** [jensstigaard/node-vmix#14]
When register listener for event `acts` it will never been called.

Testing with 
```js
connection.send('ACTS Input')

connection.on('acts', console.log); // This will never been called
```

After some digging I've found vMix 24 will Reply with `ACTS` not `ACTIVATORS` but this module seem only expecting `ACTIVATORS`

**Comment by jensstigaard** [comment]
Merged PR#15 and created alias so both on('activators',...) and on('acts', ...) will work
