### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by hrueger** [jensstigaard/node-vmix#17]
Hi @jensstigaard,
I think I found another small bug: The `autoReconnect` option seems to add a new `connect` listener every time it tries to open the socket.
It is quite simple to reproduce: Just create a vMix instance like so:
```TypeScript
this.vMix = new ConnectionTCP("localhost", { autoReconnect: true, debug: false, debugBuffers: false });
```
but don't start vMix on your machine.

After about a minute or two, you get
```
node:22384) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```
and if node was started with the `--trace-warnings` flag, you get
```
(node:21584) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at Socket.addListener (node:events:487:10)
    at Socket.Readable.on (node:internal/streams/readable:876:35)
    at Socket.once (node:events:531:8)
    at Socket.connect (node:net:976:10)
    at ConnectionTCP.connect (A:\_Source\GLUE\packages\Glue\node_modules\node-vmix\src\modules\connection-tcp.ts:757:22)
    at Timeout._onTimeout (A:\_Source\GLUE\packages\Glue\node_modules\node-vmix\src\modules\connection-tcp.ts:249:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

If you need more info or are unable to reproduce this, just let me know.

Best regards

**Comment by jensstigaard** [comment]
I think I've located the bug, however the fix was to remove the ability to wait for the promise to resolve for the function...
The fix is pushed to https://github.com/jensstigaard/node-vmix/commit/4dd5485a2ec7b48655c3bbe1a39e37862a52df03
And npm patch: [node-vmix@1.6.1](https://github.com/jensstigaard/node-vmix/commit/8f357fe625a150af0aaa8572e1eab8f57d8d8aa9)

Please test it out and ping if it has not solved the bug...

**Comment by hrueger** [comment]
Thanks a lot for the (again) very quick fix. However, I won't be able to get to this until Saturday, I hope that's fine.

**Comment by hrueger** [comment]
Hi @jensstigaard,
sorry for the delay, life has been quite busy.

I just tested it and the issue seems to be fixed now 👍 Thanks again.
