### ISSUE TITLE
Myserious Log Entries 1200001

### ISSUE THREAD

**Issue by jafny** [jensstigaard/node-vmix#5]
Hello!

First let me say thank you for this amazing module, it has helped me immensely! 

I do have a question for you. One unusual behavior I am seeing is that when I sent a tally request using connection.send('TALLY'), my console logs the number 1200001

, even though i do not have any console.log() statement attached to my connection.on('tally) or connection.on('data) functions. Any idea where this might be generating from? I am polling tally frequently and am cluttering my logs a bit. Code is below

Thanks again for this great contribution to the Vmix community!

Best,
Justin

`  async getTally() {
    return new Promise((resolve, reject) => {
      this.connection.on("error", (error) => {
        console.error("Error", error);
        reject(error);
      });
      this.connection.on("tally", (tally) => {
        this.pgmTally = tally.program[0]; // array of program inputs counts overlays, so only taking first entry.
        resolve(this.pgmTally);
      });
      this.connection.send("TALLY");
    });
  }`

**Comment by jensstigaard** [comment]
Hi Justin

I just located a console.log statement in the package in the following line:
https://github.com/jensstigaard/node-vmix/blob/master/src/modules/connection-tcp.ts#L450

I will push an update of the package later today where this is gone.

Sorry for the inconvenience.

**Comment by jafny** [comment]
No worries at all. Thanks for the quick response and thanks again for the great open source vmix utilities!

**Comment by jensstigaard** [comment]
Hi @jafny

I have now updated the package to version 1.2.3 which fixes this issue.
Please update the dependency in your project.

I will close this issue in a couple of days if you either find it resolved or have not returned with any comments.

Best regards

**Comment by jafny** [comment]
Hi @jensstigaard. I can confirm that this is now fixed. Thank you!
